version: '3'

services:
  web:
    image: nginx:alpine
    ports:
      - 8888:80
    volumes:
      - ./www:/usr/share/nginx/html
  neo4j:
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_memory_pagecache_size=2G
      - NEO4J_dbms.memory.heap.initial_size=2G
      - NEO4J_dbms_memory_heap_max__size=2G
